on:
  pull_request:
  push:
    branches:
      - main
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.23', '1.24']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...
    - name: Vet
      run: |
        go vet ./...
    - name: Test
      run: |
        go test -v -race ./...
